### ISSUE TITLE
Got issue on style for Shadow DOM

### ISSUE THREAD

**Issue by ZheFeng** [blaqbern/eclectic-syntax#4]
Hi, I got an issue when I try to set some customize style in Atom.

The style I set is

```
atom-text-editor .invisible-character, :host .invisible-character {
    color: #484848;
}
```

If I disable the Shadow DOM. It's all good. But if I enable Shadow DOM, it's not working at all.

Anyway, really appreciate this theme, really good one. Almost the best I ever found. Thanks.

**Comment by blaqbern** [comment]
Thanks for the kind words. I'll take a look at this tonight.

**Comment by blaqbern** [comment]
I looked into this. It looks like Atom changed the way atom-text-editor styles are accessed. See atom/atom#4962. I think you can fix the problem by updating your stylesheet:

``` less
// currently you have:
atom-text-editor .invisible-character, :host .invisible-character {
  color: #484848;
}

// change that to:
atom-text-editor::shadow .invisible-character {
  color: #484848;
}
```

I don't know too much about the shadow DOM, but the `:host` selector selects a shadow-host DOM element. You can read more about it in [this post on HTML5ROCKS!](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/) Anyway, styling just the `atom-text-editor .invisible-styles` worked for me.

I may need to update the theme to reflect these changes as well. See exAspArk/cozy-atom-theme#4. I'll look into this soon. In the meantime, the change above should solve your issue.

Thanks for helping to make the theme better!
